---

- hosts: all
  become: true
  tasks:


  - name: install apache2 and php support package for Ubuntu
    apt:
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


## CentOS
  - name: install httpd and php for CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: start systemctl / systemd httpd
    systemd:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: enabled httpd
    systemd:
      name: httpd
      enabled: yes
    when: ansible_distribution == "CentOS"
