---

- hosts: all
  become: true
  tasks:

#  - name: update repository index for apt   cleaned / added this to the install task
#    apt:
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"
#    when: ansible_distribution in ["Debian", "Ubuntu"]
#    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"

#  - name: install apache2 and php support package for Ubuntu shortened below
#    apt:
#      name:
#         - apache2
#         - libapache2-mod-php
#      state: latest
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php support package for Ubuntu
    package:
      name: 
         - "{{ apache_package }}"
         - "{{ php_package }}"
      state: latest
      update_cache: yes
#    when: ansible_distribution == "Ubuntu"


## CentOS

#  - name: update repository index for CentOS  added this to the install task below
#    yum:
#      update_cache: yes
#    when: ansible_distribution == "CentOS"
#    when: ansible_distribution in ["Debian", "Ubuntu"]
#    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"

#  - name: install httpd and php package for CentOS
#    yum:
#      name: 
#        - httpd
#        - php
#      state: latest
#      update_cache: yes
#    when: ansible_distribution == "CentOS"

  - name: start systemctl / systemd httpd
    systemd:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: enabled httpd
    systemd:
      name: httpd
      enabled: yes
    when: ansible_distribution == "CentOS"
