---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Ubuntu"


  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"


  - name: Stop MariaDB service
    service:
      name: mariadb
      state: stopped
    when: ansible_distribution == "Ubuntu"

  - name: Disable MariaDB service
    service:
      name: mariadb
      enabled: no
    when: ansible_distribution == "Ubuntu"

  - name: Remove MariaDB packages
    apt:
      name: "{{ item }}"
      state: absent
    loop:
      - mariadb-server
      - mariadb-client
      - mariadb-common
    when: ansible_distribution == "Ubuntu"

  - name: Remove MariaDB configuration directory
    file:
      path: /etc/mysql
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: Remove MariaDB data directory
    file:
      path: /var/lib/mysql
      state: absent
#      recurse: yes
    when: ansible_distribution == "Ubuntu"




# CentOS

  - name: Stop httpd service
    systemd:
      name: httpd
      state: stopped
    when: ansible_distribution == "CentOS"

  - name: Disable httpd service
    systemd:
      name: httpd
      enabled: no
    when: ansible_distribution == "CentOS"

  - name: remove httpd package
    yum:
      name: httpd
      state: absent
    when: ansible_distribution == "CentOS"

  - name: Remove httpd configuration files
    file:
      path: /etc/httpd
      state: absent
#      recurse: yes
    when: ansible_distribution == "CentOS"
