---
- name: Remove MariaDB directories
  hosts: all
  become: yes  # Ensure privilege escalation if required

  tasks:
    - name: Ensure the /etc/mysql directory exists and is a directory (Ubuntu)
      stat:
        path: /etc/mysql
      register: etc_mysql

    - name: Remove MariaDB configuration directory (Ubuntu)
      file:
        path: /etc/mysql
        state: absent
      when: ansible_distribution == "Ubuntu" and etc_mysql.stat.isdir is defined and etc_mysql.stat.isdir

    - name: Ensure the /var/lib/mysql directory exists and is a directory (Ubuntu)
      stat:
        path: /var/lib/mysql
      register: var_lib_mysql

    - name: Remove MariaDB data directory (Ubuntu)
      file:
        path: /var/lib/mysql
        state: absent
        recurse: yes
      when: ansible_distribution == "Ubuntu" and var_lib_mysql.stat.isdir is defined and var_lib_mysql.stat.isdir

