---

- hosts: all
  become: true
  tasks:
    - name: Remove MariaDB and related packages (Ubuntu)
      tags: db, mariadb, ubuntu
      apt:
        name:
          - mariadb-server
          - mariadb-client
          - mariadb-common
        state: absent
        purge: yes
      when: ansible_distribution == "Ubuntu"

    - name: Remove MariaDB and related packages (CentOS)
      tags: db, mariadb, centos
      yum:
        name:
          - mariadb
          - mariadb-server
          - mariadb-client
        state: absent
      when: ansible_distribution == "CentOS"

    - name: Remove Apache and PHP packages (Ubuntu)
      tags: apache, php, ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: absent
        purge: yes
      when: ansible_distribution == "Ubuntu"

    - name: Remove Apache and PHP packages (CentOS)
      tags: apache, httpd, php, centos
      yum:
        name:
          - httpd
          - php
        state: absent
      when: ansible_distribution == "CentOS"

    - name: Remove Terraform binary (Ubuntu)
      tags: terraform, ubuntu
      file:
        path: /usr/local/bin/terraform
        state: absent
      when: ansible_distribution == "Ubuntu"

    - name: Remove Samba package (Ubuntu)
      tags: samba, ubuntu
      apt:
        name: samba
        state: absent
        purge: yes
      when: ansible_distribution == "Ubuntu"

    - name: Remove Samba package (CentOS)
      tags: samba, centos
      yum:
        name: samba
        state: absent
      when: ansible_distribution == "CentOS"

    - name: Autoremove unnecessary packages (Ubuntu)
      tags: autoremove, ubuntu
      apt:
        autoremove: yes
      when: ansible_distribution == "Ubuntu"

    - name: Clean package cache (Ubuntu)
      tags: autoclean, ubuntu
      apt:
        autoclean: yes
      when: ansible_distribution == "Ubuntu"

    - name: Clean package cache (CentOS)
      tags: clean, centos
      yum:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Remove MariaDB data directory (Ubuntu)
      file:
        path: /var/lib/mysql
        state: absent
        force: yes
      when: ansible_distribution == "Ubuntu"

    - name: Remove MariaDB data directory (CentOS)
      file:
        path: /var/lib/mysql
        state: absent
        force: yes
      when: ansible_distribution == "CentOS"

    - name: Remove MariaDB configuration directory (Ubuntu)
      file:
        path: /etc/mysql
        state: absent
        force: yes
      when: ansible_distribution == "Ubuntu"

    - name: Remove MariaDB configuration directory (CentOS)
      file:
        path: /etc/my.cnf.d
        state: absent
        force: yes
      when: ansible_distribution == "CentOS"

#- hosts: all
#  become: true
#  tasks:
#    - name: Remove Simone user
#      user:
#        name: simone
#        state: absent
#      tags: always

#    - name: Remove Simone's SSH authorized keys
#      authorized_key:
#        user: simone
#        state: absent
#      tags: always

#    - name: Remove Simone's .ssh directory
#      tags: user, simone, sshdir
#      file:
#        path: /home/simone/.ssh
#        state: absent
#        recurse: yes
#      ignore_errors: yes  # Ignore errors if the .ssh directory does not exist

#    - name: Remove Simone's sudoers file
#      file:
#        path: /etc/sudoers.d/simone
#        state: absent
#      tags: always
