---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install upadtes (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name:  unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_darwin_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php support package for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
         - apache2
         - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache,centos,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


## CentOS
  - name: install httpd and php for CentOS
    tags: apache,httpd,centos
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

#  - name: start httpd (CentOS) using systemd
#    systemd:
#      name: httpd
#      state: started
#    when: ansible_distribution == "CentOS"

#  - name: enabled httpd
#    systemd:
#      name: httpd
#      enabled: yes
#    when: ansible_distribution == "CentOS"
  - name: start httpd (CentOS) using service
    tags: apache,httpd,centos
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: db,mariadb,centos
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

