---
- hosts: all
  become: true
  pre_tasks:
    - name: Install updates (CentOS)
      tags: always
      yum:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Ensure no broken packages (Ubuntu)
      command: apt install -f
      when: ansible_distribution == "Ubuntu"

    - name: Configure unpacked packages (Ubuntu)
      command: dpkg --configure -a
      when: ansible_distribution == "Ubuntu"

    - name: Autoremove unnecessary packages (Ubuntu)
      apt:
        autoremove: yes
      when: ansible_distribution == "Ubuntu"

#    - name: Check if mariadb.cnf exists (Ubuntu)
#      stat:
#        path: /etc/mysql/mariadb.cnf
#      register: mariadb_cnf
#      when: ansible_distribution == "Ubuntu"

#    - name: Create mariadb.cnf file if missing (Ubuntu)
#      file:
#        path: /etc/mysql/mariadb.cnf
#        state: touch
#      when: ansible_distribution == "Ubuntu" and not mariadb_cnf.stat.exists

- hosts: workstations
  become: true
  tasks:
    - name: Install unzip (Ubuntu or ContOS)
      tags: unzip, workstations
      package:
        name: unzip
        state: present

    - name: Install Terraform (Ubuntu)
      tags: terraform, ubuntu
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
        owner: root
        group: root

- hosts: web_servers
  become: true
  tasks:
    - name: Install apache2 and PHP support package (Ubuntu)
      tags: apache, apache2, ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Copy default HTML file for site
      tags: apache, centos, httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Install httpd and PHP (CentOS)
      tags: apache, httpd, centos
      yum:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Start and enable httpd (CentOS)
      tags: apache, httpd, centos
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:
    - name: Install MariaDB package (CentOS)
      tags: db, mariadb, centos
      yum:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Install MariaDB package (Ubuntu)
      tags: db, mariadb, ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: Install Samba package
      tags: samba
      package:
        name: samba
        state: latest

