- name: install apache2 and php support package for Ubuntu
  tags: apache,apache2,ubuntu
  apt:
    name:
       - apache2
       - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

#centos

- name: copy default html file for site
  tags: apache,centos,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: install httpd and php for CentOS
  tags: apache,httpd,centos
  yum:
    name:
      - httpd
      - php
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: start httpd (CentOS) using service
  tags: apache,httpd,centos
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: change email address for admin (CentOS)
  tags: apache, apache2, httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@nowhere.net
  when: ansible_distribution == "CentOS"
  register: httpd_var

- name: restart httpd (CentOS)
  tags: apachhe, apache2, httpd, centos
  service:
    name: httpd
    state: restarted
  when: httpd_var.changed

- name: copy default html file for site
  tags: apache,centos,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

